# Generated by Django 5.0.7 on 2024-08-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ask_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_qa',
            name='detail_answer',
            field=models.TextField(blank=True, null=True, verbose_name='คำตอบ'),
        ),
    ]
